name: ds-test

channels:
    - conda-forge

dependencies:
    - python=3.13
    - numpy
    - geopandas
    - rasterio
    - matplotlib
    - tqdm
    - pip
    - jupyterlab
    - xlrd
    - pyproj
    - xarray
    - rioxarray   
    - igraph
    - pip:
        - contextily
        - openpyxl
        
