name: damagescanner

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - numpy
        - geopandas
        - rasterio
        - matplotlib
        - tqdm
        - pip
        - jupyterlab
        - xlrd
        - pyproj
        - xarray
        - rioxarray   
          
