name: damagescanner

channels:
    - conda-forge

dependencies:
    - python=3.11
    - numpy
    - geopandas
    - rasterio
    - matplotlib
    - tqdm
    - pip
    - jupyterlab
    - xlrd
    - pyproj
    - xarray
    - rioxarray
        
