site_name: DamageScanner
repo_url: https://github.com/VU-IVM/DamageScanner
repo_name: DamageScanner
site_description: Damage Assessments for Natural Hazards
site_author: Elco Koks, Jens de Bruijn
copyright:
  '<span>
    <i> Institute for Environmental Studies, Vrije Universiteit Amsterdam </i>
    <br>
    Copyright &copy; 
    <script>document.write(new Date().getFullYear())</script> 
    Elco Koks & Jens de Bruijn
  </span>'

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
          setup_commands:
            - import os
            - import sys
            - sys.path.insert(0, os.path.abspath('.'))

nav:
  - Getting Started: index.md
  - How it works:
      - Overview: how-to/overview.md
      - Raster-based approach: how-to/raster.md
      - Vector-based approach: how-to/vector.md
      - Coupling with OSM: how-to/osm.md
  - API Reference: api.md


markdown_extensions:
  - markdown_include.include
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.magiclink

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/earth
    repo: material/github
  favicon: material/earth-box-plus
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections  # Shows all top-level sections in sidebar
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

extra_javascript:
  - javascripts/set-body-class.js

extra_css:
  - stylesheets/extra.css


