site_name: DamageScanner
repo_url: https://github.com/VU-IVM/DamageScanner
repo_name: DamageScanner
site_description: Damage Assessments for Natural Hazards
site_author: Elco Koks, Jens de Bruijn

plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import os
            - import sys
            - sys.path.insert(0, os.path.abspath('.'))

nav:
  - Getting Started: index.md

markdown_extensions:
  - markdown_include.include
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.magiclink

theme:
  name: material
  icon:
    logo: material/earth
    repo: material/github
  favicon: material/earth-box-plus
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: black
      accent: white
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  generator: false
