[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "damagescanner"
version = "1.0.0"
authors = [
    {name = "Elco Koks", email = "elco.koks@vu.nl"},
    {name = "Jens de Bruijn", email = "jens.de.bruijn@vu.nl"},
]

license = {text = "MIT License"}
description = "Direct damage assessments for natural hazards"
keywords = ["GIS", "natural hazards", "damage assessment", "remote sensing", "raster", "vector", "geospatial"]
classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: GIS",
        "Topic :: Utilities",
    ]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "numpy",
    "geopandas",
    "rasterio",
    "matplotlib",
    "tqdm",
    "xlrd",
    "pyproj",
    "xarray",
    "rioxarray",
    "openpyxl",
    "exactextract"
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
tests = ["pytest", "pyarrow", "netcdf4"]
docs = ["jupyter"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[project.urls]
"Homepage" = "https://github.com/ElcoK/DamageScanner"
"Documentation" = "https://damagescanner.readthedocs.io/en/latest/"
