[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "damagescanner"
version = "1.0.1"
authors = [
    {name = "Elco Koks", email = "elco.koks@vu.nl"},
    {name = "Jens de Bruijn", email = "jens.de.bruijn@vu.nl"},
]

license = {text = "MIT License"}
description = "Direct damage assessments for natural hazards"
keywords = ["GIS", "natural hazards", "damage assessment", "remote sensing", "raster", "vector", "geospatial"]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Utilities",
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "numpy>=2.3.0",
    "geopandas>=1.0.0",
    "rasterio>=1.5.0",
    "matplotlib>=3.10.0",
    "tqdm>=4.67.0",
    "xlrd>=2.0.0",
    "pyproj>=3.7.2",
    "xarray>=2025.0.0",
    "rioxarray>=0.20",
    "openpyxl>=2.0.0",
    "exactextract>=0.3.0"
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.2",
    "ty>=0.0.17"
]
tests = ["pytest>=9.0.0", "pyarrow>=22.0.0", "netcdf4>=1.7.4"]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.2",
    "mkdocs-include-markdown-plugin>=7.2.1",
    "markdown-include>=0.8.1",
    "mkdocs-jupyter>=0.25.0",
    "mkdocstrings[python]>=1.0.3",
    "mike>=2.1.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[project.urls]
"Homepage" = "https://github.com/VU-IVM/DamageScanner"
"Documentation" = "https://vu-ivm.github.io/DamageScanner/"

[tool.ruff.lint]
select = [
    "ANN002",
    "ANN003",
    "ANN204",
    "ANN205",
    "ANN206",
    "DOC102",
    "DOC201",
    "DOC202",
    "DOC402",
    "DOC501",
    "DOC502",
    "ANN001",
    "ANN003",
    "ANN201",
    "ANN202",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D201",
    "D202",
    "D204",
    "D205",
    "D206",
    "D207",
    "D208",
    "D209",
    "D210",
    "D211",
    "D300",
    "D400",
    "D405",
    "D406",
    "D415",
    "D416",
    "D417",
    "D419",
    "F401",
    "UP006",
    "UP007",
    "UP008",
    "UP009",
    "UP010",
    "UP012",
    "UP017",
    "UP022",
    "UP029",
    "UP037",
    "UP044",
    "UP045",
]
extend-select = ["I"]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["geb"]
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"
