[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "damagescanner"
version = "1.0.0b2"
authors = [
    {name = "Elco Koks", email = "elco.koks@vu.nl"},
    {name = "Jens de Bruijn", email = "jens.de.bruijn@vu.nl"},
]

license = {text = "MIT License"}
description = "Direct damage assessments for natural hazards"
keywords = ["GIS", "natural hazards", "damage assessment", "remote sensing", "raster", "vector", "geospatial"]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Utilities",
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "numpy>=2.0.0",
    "geopandas>=1.0.0",
    "rasterio",
    "matplotlib",
    "tqdm",
    "xlrd",
    "pyproj",
    "xarray",
    "rioxarray",
    "openpyxl",
    "exactextract>=0.3.0"
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.2",
    "ty"
]
tests = ["pytest", "pyarrow", "netcdf4"]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-include-markdown-plugin",
    "markdown-include",
    "mkdocs-jupyter",
    "mkdocstrings[python]",
    "mike",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[project.urls]
"Homepage" = "https://github.com/VU-IVM/DamageScanner"
"Documentation" = "https://vu-ivm.github.io/DamageScanner/"

[tool.ruff.lint]
select = [
    "ANN002",
    "ANN003",
    "ANN204",
    "ANN205",
    "ANN206",
    "DOC102",
    "DOC201",
    "DOC202",
    "DOC402",
    "DOC501",
    "DOC502",
    "ANN001",
    "ANN003",
    "ANN201",
    "ANN202",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D201",
    "D202",
    "D204",
    "D205",
    "D206",
    "D207",
    "D208",
    "D209",
    "D210",
    "D211",
    "D300",
    "D400",
    "D405",
    "D406",
    "D415",
    "D416",
    "D417",
    "D419",
    "F401",
    "UP006",
    "UP007",
    "UP008",
    "UP009",
    "UP010",
    "UP012",
    "UP017",
    "UP022",
    "UP029",
    "UP037",
    "UP044",
    "UP045",
]
extend-select = ["I"]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["geb"]
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "google"