name: Python package

on: [push]

defaults:
  run:
    shell: bash -el {0}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=3.10 numpy`
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            cartopy
            geopandas
          cache-environment: true
          init-shell: >-
            bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[tests]"
          python -m pip install ruff
      - name: Lint with ruff
        continue-on-error: true
        run: |
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py39 .
      - name: Test with pytest
        run: |
          pytest
