name: pytest

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Install the project
        run: uv sync --group dev --group tests
      
      - name: Run tests
        run: uv run pytest -s