name: pytest

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      # Install latest uv version using the installer
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install the project
      run: uv sync --dev
    - name: Run tests
      run: uv run pytest -s